### ISSUE TITLE
`AssertionError: would build wheel with unsupported tag ('cp312', 'cp311', 'macosx_11_0_arm64')`

### ISSUE THREAD

**Issue by justinTM** [mtkennerly/poetry-dynamic-versioning#168]
devbox version 0.9.1
poetry version 1.7.1
python version 3.11.6
macOS version 14.1.2

```console
poetry self add "poetry-dynamic-versioning[plugin]" > bug-report.txt
```

```console
# bug-report.txt
Using version ^1.2.0 for poetry-dynamic-versioning

Updating dependencies
Resolving dependencies...

Package operations: 3 installs, 14 updates, 0 removals

  • Updating certifi (2023.11.17 /private/tmp/python-certifi-20231211-18102-76ipel/certifi-2023.11.17 -> 2024.2.2)
  • Updating more-itertools (10.1.0 /private/tmp/keyring--more-itertools-20231113-5648-1qd1yjf/more-itertools-10.1.0 -> 10.2.0)
  • Updating pycparser (2.21 /private/tmp/pycparser-20231211-25057-cypg40/pycparser-2.21 -> 2.21)
  • Updating urllib3 (2.1.0 -> 2.2.1)
  • Updating cffi (1.16.0 /private/tmp/cffi-20231211-40239-j25k6o/cffi-1.16.0 -> 1.16.0)
  • Updating distlib (0.3.8 /private/tmp/python-distlib-20231212-4938-trhlvy/distlib-0.3.8 -> 0.3.8)
  • Updating jaraco-classes (3.3.0 /private/tmp/keyring--jaraco-classes-20231113-5648-52cmva/jaraco.classes-3.3.0 -> 3.3.1)
  • Updating filelock (3.13.1 /private/tmp/python-filelock-20231112-5622-k62fq8/filelock-3.13.1/dist/filelock-3.13.1-py3-none-any.whl -> 3.13.1)
  • Downgrading platformdirs (4.1.0 /private/tmp/python-platformdirs-20231204-5317-3q4okz/platformdirs-4.1.0 -> 3.11.0)
  • Updating packaging (23.2 /private/tmp/python-packaging-20231211-10905-adsfgp/packaging-23.2 -> 23.2)
  • Updating keyring (24.3.0 /private/tmp/keyring-20231112-5648-1a0k1u8/keyring-24.3.0 -> 24.3.0)
  • Updating virtualenv (20.25.0 /private/tmp/virtualenv-20231201-5488-j5rd10/virtualenv-20.25.0 -> 20.25.0)
  • Updating xattr (0.10.1 /private/tmp/poetry--xattr-20231117-6920-7lc93m/xattr-0.10.1 -> 0.10.1)

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-arm64-cpython-312
  creating build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/lib_build.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/compat.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/lib.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/__init__.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/tool.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  copying xattr/pyxattr_compat.py -> build/lib.macosx-11.0-arm64-cpython-312/xattr
  running build_ext
  generating cffi module 'build/temp.macosx-11.0-arm64-cpython-312/_lib.c'
  creating build/temp.macosx-11.0-arm64-cpython-312
  building '_lib' extension
  creating build/temp.macosx-11.0-arm64-cpython-312/build
  creating build/temp.macosx-11.0-arm64-cpython-312/build/temp.macosx-11.0-arm64-cpython-312
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/qmcw4rlkn8162d6grcjkyrgyj982xg93-libxcrypt-4.4.36/include -I/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/include -I/nix/store/z0nnwdh4p692yvf3qgwgj3bn78w99q6y-python3-3.11.6/include/python3.11 -c build/temp.macosx-11.0-arm64-cpython-312/_lib.c -o build/temp.macosx-11.0-arm64-cpython-312/build/temp.macosx-11.0-arm64-cpython-312/_lib.o
  clang -bundle -undefined dynamic_lookup -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.4.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.4.4/lib -L/nix/store/qmcw4rlkn8162d6grcjkyrgyj982xg93-libxcrypt-4.4.36/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.23/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.43.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-8.2p7/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.4/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-3.0.12/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-apple-framework-SystemConfiguration-11.0.0/lib -L/nix/store/rx9la6wjll46fpl45y09z2nm3n3y4ir9-tzdata-2023c/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.4.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.4.4/lib -L/nix/store/qmcw4rlkn8162d6grcjkyrgyj982xg93-libxcrypt-4.4.36/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.23/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.43.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-8.2p7/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.4/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-3.0.12/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-apple-framework-SystemConfiguration-11.0.0/lib -L/nix/store/rx9la6wjll46fpl45y09z2nm3n3y4ir9-tzdata-2023c/lib build/temp.macosx-11.0-arm64-cpython-312/build/temp.macosx-11.0-arm64-cpython-312/_lib.o -L/nix/store/z0nnwdh4p692yvf3qgwgj3bn78w99q6y-python3-3.11.6/lib -o build/lib.macosx-11.0-arm64-cpython-312/xattr/_lib.abi3.so
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.4.5/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.4.4/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.23/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.43.2/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-8.2p7/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.4/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-3.0.12/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-apple-framework-SystemConfiguration-11.0.0/lib'
  ld: warning: directory not found for option '-L/nix/store/rx9la6wjll46fpl45y09z2nm3n3y4ir9-tzdata-2023c/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.4.5/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.4.4/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.23/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.43.2/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-8.2p7/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.4/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-3.0.12/lib'
  ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-apple-framework-SystemConfiguration-11.0.0/lib'
  ld: warning: directory not found for option '-L/nix/store/rx9la6wjll46fpl45y09z2nm3n3y4ir9-tzdata-2023c/lib'
  installing to build/bdist.macosx-11.0-arm64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-11.0-arm64
  creating build/bdist.macosx-11.0-arm64/wheel
  creating build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/lib_build.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/compat.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/lib.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/_lib.abi3.so -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/__init__.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/tool.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  copying build/lib.macosx-11.0-arm64-cpython-312/xattr/pyxattr_compat.py -> build/bdist.macosx-11.0-arm64/wheel/xattr
  running install_egg_info
  running egg_info
  writing xattr.egg-info/PKG-INFO
  writing dependency_links to xattr.egg-info/dependency_links.txt
  writing entry points to xattr.egg-info/entry_points.txt
  writing requirements to xattr.egg-info/requires.txt
  writing top-level names to xattr.egg-info/top_level.txt
  reading manifest file 'xattr.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  writing manifest file 'xattr.egg-info/SOURCES.txt'
  Copying xattr.egg-info to build/bdist.macosx-11.0-arm64/wheel/xattr-0.10.1-py3.12.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 34, in <module>
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
      super().run_command(command)
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 405, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
                                    ^^^^^^^^^^^^^^
    File "/private/var/folders/d5/wymf6s8566775p3bh18pkc140000gn/T/tmpbzc_popd/.venv/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 354, in get_tag
      assert (
  AssertionError: would build wheel with unsupported tag ('cp312', 'cp311', 'macosx_11_0_arm64')
  

  at /opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with xattr (0.10.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "xattr (==0.10.1)"'.
```

**Comment by mtkennerly** [comment]
I don't understand why it's updating to the same version of xattr here. The `/private/tmp/poetry...` path is unusual to me:

```
  • Updating xattr (0.10.1 /private/tmp/poetry--xattr-20231117-6920-7lc93m/xattr-0.10.1 -> 0.10.1)
```

I'm not familiar with Devbox. Does it create a virtual environment for Poetry? If not, then that may be the issue.

**Comment by justinTM** [comment]
i fixed by wiping out my virtual env, poetry lock, and devbox cache, then reinstalled plugin :)
