### ISSUE TITLE
Doesn't work with `pip` when pyproject.toml is in a repository subdirectory

### ISSUE THREAD

**Issue by aantn** [mtkennerly/poetry-dynamic-versioning#46]
```bash
$ pip3 install . --user --force
Processing /Projects/test/src
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/tmpndenwgx6
         cwd: /private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-req-build-5hg4fjfe
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/poetry_dynamic_versioning/__init__.py", line 353, in alt_poetry_create
        _state.project(name).version = _get_version(config)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/poetry_dynamic_versioning/__init__.py", line 169, in _get_version
        version = Version.from_vcs(
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 890, in from_vcs
        return cls._do_vcs_callback(vcs, pattern, latest_tag, tag_dir)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 906, in _do_vcs_callback
        return mapping[vcs](**kwargs)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 485, in from_git
        _detect_vcs(Vcs.Git)
      File "/private/var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/pip-build-env-m9lmbts8/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 175, in _detect_vcs
        raise RuntimeError(
    RuntimeError: This does not appear to be a Git project
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/9d/w12tylk1403bjxd6k93pdqp80000gn/T/tmpndenwgx6 Check the logs for full command output.
```

**Comment by aantn** [comment]
The root cause of this seems to be that pip is copying the project to a temporary location but it isn't copying the root of the repository (because it shouldn't) which contains the .git directory. Any ideas for working around this?

**Comment by aantn** [comment]
Ok, it looks like `pip3 install --use-feature=in-tree-build` fixes this. Closing this, but might be worth adding it to the docs.

**Comment by mtkennerly** [comment]
Thanks! I didn't know about that `in-tree-build` option, but I'll add it to the documentation.
